# ───────────── configs/cost.yml ─────────────
gain: [300, 250, 200]   # 1着あたり平均粗利（円/点）
h:    5                 # 保管コスト（円/点）
w:    50                # 廃棄コスト（円/点）
cap:  1000              # 月あたり最大仕入れ点数
